version: '2.3'

services:
  database:
    image: mysql:8.0
    container_name: mysql_db
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: